//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSankAlumni.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAlumniReg
    {
        public int AlumniId { get; set; }
        public string AlumniName { get; set; }
        public string eSankalpId { get; set; }
        public string PassoutYr { get; set; }
        public string DOB { get; set; }
        public string TotalExp { get; set; }
        public string CurrentCompany { get; set; }
        public string CTC { get; set; }
        public string Photo { get; set; }
        public string City { get; set; }
        public string Address { get; set; }
        public string CollegeName { get; set; }
        public string Education { get; set; }
        public string IsActive { get; set; }
    }
}
