//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSankAlumni.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFeedback
    {
        public int FeedbackId { get; set; }
        public string StudentName { get; set; }
        public int eSankalpId { get; set; }
        public int LectureId { get; set; }
        public int QueId { get; set; }
        public string Rating { get; set; }
        public System.DateTime FeedbackDate { get; set; }
    }
}
