//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSankAlumni.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLecture
    {
        public int LectureId { get; set; }
        public string LectureDate { get; set; }
        public string TimeSlot { get; set; }
        public string Topic { get; set; }
        public string Details { get; set; }
        public string LectureById { get; set; }
        public string LecturePhoto1 { get; set; }
        public string LecturePhoto2 { get; set; }
        public string NotesDocument { get; set; }
        public string TestDocument { get; set; }
        public string IsActive { get; set; }
    }
}
